# Generated by Django 5.2.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify

# --- INICIO DE LA SECCIÓN DE DATOS ---

ESRB_RATINGS_DATA = {
    'E': 'Everyone (Para todos)', 'E10+': 'Everyone 10+ (Para todos 10+)',
    'T': 'Teen (Adolescentes)', 'M': 'Mature 17+ (Maduro 17+)'
}

PRODUCTOS_DATA = [
    # Juegos de PlayStation 5
    {'nombre': 'Stellar Blade', 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Aventura de acción post-apocalíptica con combate trepidante.'},
    {'nombre': 'Rise of the Ronin', 'precio': 69990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Ambientado en el Japón del siglo XIX, este juego de acción ofrece combates intensos y una narrativa profunda.'},
    {'nombre': 'Final Fantasy VII Rebirth', 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'rating': 'T', 'descripcion': 'La segunda entrega del proyecto remake de FINAL FANTASY VII, con una historia inolvidable y un vasto mundo por explorar.'},
    {'nombre': 'Helldivers 2', 'precio': 39990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Shooter cooperativo en tercera persona donde luchas por la libertad en una galaxia hostil.'},
    {'nombre': "Elden Ring Shadow of the Erdtree Collector's Edition", 'precio': 249990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Edición coleccionista de la expansión de Elden Ring, incluye figura y libro de arte.'},
    {'nombre': 'Elden Ring Shadow of the Erdtree Edition', 'precio': 69990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Incluye el juego base Elden Ring y la expansión Shadow of the Erdtree.'},
    {'nombre': 'Shin Megami Tensei V: Vengeance', 'precio': 59990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'La versión definitiva de Shin Megami Tensei V, con una nueva ruta argumental y mejoras jugables.'},
    {'nombre': 'TopSpin 2K25', 'precio': 59990, 'categoria': 'Juegos PlayStation 5', 'rating': 'E', 'descripcion': 'El regreso de la aclamada saga de tenis, con realismo y jugabilidad mejorados.'},
    {'nombre': 'Sand Land', 'precio': 56990, 'categoria': 'Juegos PlayStation 5', 'rating': 'T', 'descripcion': 'Basado en la obra de Akira Toriyama, este juego combina acción, exploración y humor en un mundo desértico.'},
    {'nombre': 'Eiyuden Chronicle: Hundred Heroes', 'precio': 49990, 'categoria': 'Juegos PlayStation 5', 'rating': 'E10+', 'descripcion': 'Un JRPG moderno con la estética y el espíritu de los clásicos del género.'},
    {'nombre': "Dragon's Dogma 2", 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'rating': 'M', 'descripcion': 'Un RPG de acción para un jugador que te permite elegir tu propia experiencia.'},
    {'nombre': 'One Piece Odyssey', 'precio': 42990, 'categoria': 'Juegos PlayStation 5', 'rating': 'T', 'descripcion': 'Aventura RPG protagonizada por Luffy y la tripulación del Sombrero de Paja, con historia original y combates por turnos.'},
    {'nombre': 'PSVR2 Horizon Call Of The Mountain Bundle', 'precio': 624990, 'categoria': 'Juegos PlayStation 5', 'rating': None, 'descripcion': 'Pack de realidad virtual que incluye el nuevo visor PSVR2 y el juego Horizon Call of the Mountain.'},
    {'nombre': 'Princess Peach: Showtime!', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E', 'descripcion': 'Peach se convierte en la estrella del espectáculo, asumiendo múltiples transformaciones para salvar el teatro.'},
    {'nombre': 'Mario vs. Donkey Kong', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E10+', 'descripcion': 'El clásico juego de puzles y plataformas regresa con gráficos renovados.'},
    {'nombre': 'The Legend of Zelda: Tears of the Kingdom', 'precio': 59990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E10+', 'descripcion': 'Una aventura épica a través de la tierra y los cielos de Hyrule te espera.'},
    {'nombre': 'Super Mario Bros. Wonder', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E', 'descripcion': 'La nueva evolución de los juegos de Mario en 2D, con las sorprendentes Flores Maravilla.'},
    {'nombre': 'Endless Ocean Luminous', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E', 'descripcion': 'Sumérgete en un misterioso mundo submarino que cambia con cada inmersión.'},
    {'nombre': 'Another Code: Recollection', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'T', 'descripcion': 'Resuelve los misterios del pasado de Ashley Mizuki Robins en esta colección remasterizada.'},
    {'nombre': 'Super Bomberman R 2', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'rating': 'E10+', 'descripcion': 'Clásico multijugador con nuevas funciones, niveles y modos de juego para disfrutar en familia o con amigos.'},
    {'nombre': 'WWE 2K24', 'precio': 59990, 'categoria': 'Juegos PlayStation 4', 'rating': 'T', 'descripcion': 'Revive los momentos más grandes de WrestleMania en 2K Showcase of the Immortals.'},
    {'nombre': 'Persona 3 Reload', 'precio': 64990, 'categoria': 'Juegos PlayStation 4', 'rating': 'M', 'descripcion': 'Sumérgete en la Hora Oscura y despierta los poderes de tu corazón en este remake del icónico RPG.'},
    {'nombre': 'Like a Dragon: Infinite Wealth', 'precio': 64990, 'categoria': 'Juegos PlayStation 4', 'rating': 'M', 'descripcion': 'Dos héroes extraordinarios unidos por el destino en una aventura que se extiende por el Pacífico.'},
    {'nombre': 'Resident Evil 4', 'precio': 44990, 'categoria': 'Juegos PlayStation 4', 'rating': 'M', 'descripcion': 'La supervivencia es solo el comienzo en esta reinvención del clásico de terror.'},
    {'nombre': 'Mortal Kombat 1', 'precio': 49990, 'categoria': 'Juegos PlayStation 4', 'rating': 'M', 'descripcion': 'Descubre un nuevo universo de Mortal Kombat renacido, creado por el Dios del Fuego Liu Kang.'},
    {'nombre': "Jojo's Bizarre Adventure: All-Star Battle R", 'precio': 181990, 'categoria': 'Juegos PlayStation 4', 'rating': 'T', 'descripcion': 'Juego de lucha basado en el famoso anime JoJo\'s Bizarre Adventure, con personajes icónicos y mecánicas espectaculares.'},
    {'nombre': 'Demon Slayer: The Hinokami Chronicles', 'precio': 41990, 'categoria': 'Juegos PlayStation 4', 'rating': 'T', 'descripcion': 'Acción intensa en este título basado en la popular serie Demon Slayer, sigue la historia de Tanjiro Kamado.'},
    {'nombre': 'The Callisto Protocol', 'precio': 39990, 'categoria': 'Juegos de PC', 'rating': 'M', 'descripcion': 'Terror espacial con gráficos de última generación, una experiencia envolvente para los fans de la ciencia ficción.'},
    {'nombre': 'Payday 3', 'precio': 39990, 'categoria': 'Juegos de PC', 'rating': 'M', 'descripcion': 'Juego cooperativo de acción y estrategia donde planeas y ejecutas robos con precisión.'},
    {'nombre': 'Star Wars Outlaws', 'precio': 69990, 'categoria': 'Juegos de PC', 'rating': 'T', 'descripcion': 'Explora el universo Star Wars en este juego de mundo abierto lleno de aventuras y decisiones morales.'},
    {'nombre': 'Consola Nintendo Switch OLED The Legend of Zelda: Tears of the Kingdom', 'precio': 349990, 'categoria': 'Consolas Nintendo Switch', 'rating': None, 'descripcion': 'Edición especial de la consola con motivos del aclamado juego.'},
    {'nombre': 'Consola Nintendo Switch 1.1 Neon', 'precio': 299990, 'categoria': 'Consolas Nintendo Switch', 'rating': None, 'descripcion': 'La versátil consola de Nintendo en su versión estándar con Joy-Cons color neón.'},
    {'nombre': 'Fuente de Poder para Consola Wii Multivoltaje', 'precio': 12990, 'categoria': 'Accesorios Wii', 'rating': None, 'descripcion': 'Fuente de poder de reemplazo para la consola Nintendo Wii, compatible con diferentes voltajes.'},
    {'nombre': 'Carta Pokémon TCG: Charizard ex - SV4.5 Paldean Fates', 'precio': 39990, 'categoria': 'Cartas TCG', 'rating': None, 'descripcion': 'Carta individual de alta rareza del popular juego de cartas coleccionables Pokémon.'},
    {'nombre': 'Disney Lorcana: Booster Box The First Chapter', 'precio': 149990, 'categoria': 'Cartas TCG', 'rating': None, 'descripcion': 'Caja sellada con 24 sobres de la primera edición del juego de cartas Disney Lorcana.'},
    {'nombre': 'Star Wars: Unlimited - Caja de Sobres', 'precio': 129990, 'categoria': 'Cartas TCG', 'rating': None, 'descripcion': 'Caja sellada con 24 sobres del nuevo juego de cartas coleccionables de Star Wars.'},
]

def poblar_datos(apps, schema_editor):
    Categoria = apps.get_model('core', 'Categoria')
    Producto = apps.get_model('core', 'Producto')

    categorias_creadas = {}
    for item in PRODUCTOS_DATA:
        nombre_cat = item['categoria']
        if nombre_cat not in categorias_creadas:
            slug = slugify(nombre_cat)
            cat_obj, _ = Categoria.objects.get_or_create(nombre=nombre_cat, defaults={'slug': slug})
            categorias_creadas[nombre_cat] = cat_obj

    for item in PRODUCTOS_DATA:
        categoria_obj = categorias_creadas[item['categoria']]
        
        # Generar tags automáticamente a partir del nombre y la categoría
        tags_nombre = item['nombre'].lower().split()
        tags_categoria = item['categoria'].lower().split()
        stop_words = {'de', 'la', 'el', 'y', 'con', 'para', 'juegos', 'edition', 'a', 'un'}
        tags = set(tags_nombre + tags_categoria) - stop_words
        tags_str = ", ".join(list(tags))

        Producto.objects.get_or_create(
            nombre=item['nombre'],
            defaults={
                'precio': item['precio'],
                'descripcion': item.get('descripcion', ''),
                'categoria': categoria_obj,
                'tags': tags_str,
                'stock': 20,
                'activo': True,
            }
        )

# --- CLASE DE MIGRACIÓN (Generada por Django) ---
class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria')),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # --- OPERACIÓN DE POBLADO DE DATOS ---
        migrations.RunPython(poblar_datos),
    ]