# Generated by Django 5.2.2 on 2025-06-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
    ]
from django.db import migrations
from django.utils.text import slugify

# --- DATOS PARA POBLAR ---
PRODUCTOS_DATA = [
    # Juegos de PlayStation 5
    {'nombre': 'Stellar Blade', 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, accion, aventura', 'descripcion': 'Aventura de acción post-apocalíptica con combate trepidante.'},
    {'nombre': 'Rise of the Ronin', 'precio': 69990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, ronin, japon, accion', 'descripcion': 'Ambientado en el Japón del siglo XIX, este juego de acción ofrece combates intensos y una narrativa profunda.'},
    {'nombre': 'Final Fantasy VII Rebirth', 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, final fantasy, ffvii, rpg', 'descripcion': 'La segunda entrega del proyecto remake de FINAL FANTASY VII, con una historia inolvidable y un vasto mundo por explorar.'},
    {'nombre': 'Helldivers 2', 'precio': 39990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, shooter, cooperativo', 'descripcion': 'Shooter cooperativo en tercera persona donde luchas por la libertad en una galaxia hostil.'},
    {'nombre': "Elden Ring Shadow of the Erdtree Collector's Edition", 'precio': 249990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, elden ring, coleccionista', 'descripcion': 'Edición coleccionista de la expansión de Elden Ring, incluye figura y libro de arte.'},
    {'nombre': 'Elden Ring Shadow of the Erdtree Edition', 'precio': 69990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, elden ring, dlc', 'descripcion': 'Incluye el juego base Elden Ring y la expansión Shadow of the Erdtree.'},
    {'nombre': 'Shin Megami Tensei V: Vengeance', 'precio': 59990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, smt, rpg, atlus', 'descripcion': 'La versión definitiva de Shin Megami Tensei V, con una nueva ruta argumental y mejoras jugables.'},
    {'nombre': 'TopSpin 2K25', 'precio': 59990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, tenis, deportes', 'descripcion': 'El regreso de la aclamada saga de tenis, con realismo y jugabilidad mejorados.'},
    {'nombre': 'Sand Land', 'precio': 56990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, akira toriyama, rpg', 'descripcion': 'Basado en la obra de Akira Toriyama, este juego combina acción, exploración y humor en un mundo desértico.'},
    {'nombre': 'Eiyuden Chronicle: Hundred Heroes', 'precio': 49990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, jrpg, suikoden', 'descripcion': 'Un JRPG moderno con la estética y el espíritu de los clásicos del género.'},
    {'nombre': "Dragon's Dogma 2", 'precio': 64990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, rpg, accion, capcom', 'descripcion': 'Un RPG de acción para un jugador que te permite elegir tu propia experiencia.'},
    {'nombre': 'One Piece Odyssey', 'precio': 42990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, one piece, anime, rpg', 'descripcion': 'Aventura RPG protagonizada por Luffy y la tripulación del Sombrero de Paja, con historia original y combates por turnos.'},
    {'nombre': 'PSVR2 Horizon Call Of The Mountain Bundle', 'precio': 624990, 'categoria': 'Juegos PlayStation 5', 'tags': 'ps5, psvr2, vr, realidad virtual', 'descripcion': 'Pack de realidad virtual que incluye el nuevo visor PSVR2 y el juego Horizon Call of the Mountain.'},
    {'nombre': 'Princess Peach: Showtime!', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, peach, mario', 'descripcion': 'Peach se convierte en la estrella del espectáculo, asumiendo múltiples transformaciones para salvar el teatro.'},
    {'nombre': 'Mario vs. Donkey Kong', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, mario, puzzle', 'descripcion': 'El clásico juego de puzles y plataformas regresa con gráficos renovados.'},
    {'nombre': 'The Legend of Zelda: Tears of the Kingdom', 'precio': 59990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, zelda, totk', 'descripcion': 'Una aventura épica a través de la tierra y los cielos de Hyrule te espera.'},
    {'nombre': 'Super Mario Bros. Wonder', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, mario, plataformas', 'descripcion': 'La nueva evolución de los juegos de Mario en 2D, con las sorprendentes Flores Maravilla.'},
    {'nombre': 'Endless Ocean Luminous', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, relax, exploracion', 'descripcion': 'Sumérgete en un misterioso mundo submarino que cambia con cada inmersión.'},
    {'nombre': 'Another Code: Recollection', 'precio': 54990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, misterio, aventura grafica', 'descripcion': 'Resuelve los misterios del pasado de Ashley Mizuki Robins en esta colección remasterizada.'},
    {'nombre': 'Super Bomberman R 2', 'precio': 49990, 'categoria': 'Juegos Nintendo Switch', 'tags': 'switch, nintendo, bomberman, multiplayer', 'descripcion': 'Clásico multijugador con nuevas funciones, niveles y modos de juego para disfrutar en familia o con amigos.'},
    {'nombre': 'WWE 2K24', 'precio': 59990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, lucha, wwe, deportes', 'descripcion': 'Revive los momentos más grandes de WrestleMania en 2K Showcase of the Immortals.'},
    {'nombre': 'Persona 3 Reload', 'precio': 64990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, persona, atlus, rpg', 'descripcion': 'Sumérgete en la Hora Oscura y despierta los poderes de tu corazón en este remake del icónico RPG.'},
    {'nombre': 'Like a Dragon: Infinite Wealth', 'precio': 64990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, yakuza, like a dragon, rpg', 'descripcion': 'Dos héroes extraordinarios unidos por el destino en una aventura que se extiende por el Pacífico.'},
    {'nombre': 'Resident Evil 4', 'precio': 44990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, resident evil, terror, survival horror', 'descripcion': 'La supervivencia es solo el comienzo en esta reinvención del clásico de terror.'},
    {'nombre': 'Mortal Kombat 1', 'precio': 49990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, mortal kombat, lucha, peleas', 'descripcion': 'Descubre un nuevo universo de Mortal Kombat renacido, creado por el Dios del Fuego Liu Kang.'},
    {'nombre': "Jojo's Bizarre Adventure: All-Star Battle R", 'precio': 181990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, jojo, anime, lucha', 'descripcion': 'Juego de lucha basado en el famoso anime JoJo\'s Bizarre Adventure.'},
    {'nombre': 'Demon Slayer: The Hinokami Chronicles', 'precio': 41990, 'categoria': 'Juegos PlayStation 4', 'tags': 'ps4, demon slayer, kimetsu no yaiba, anime', 'descripcion': 'Acción intensa en este título basado en la popular serie Demon Slayer.'},
    {'nombre': 'The Callisto Protocol', 'precio': 39990, 'categoria': 'Juegos de PC', 'tags': 'pc, terror, espacial, survival horror', 'descripcion': 'Terror espacial con gráficos de última generación.'},
    {'nombre': 'Payday 3', 'precio': 39990, 'categoria': 'Juegos de PC', 'tags': 'pc, shooter, cooperativo, robos', 'descripcion': 'Juego cooperativo de acción y estrategia donde planeas y ejecutas robos con precisión.'},
    {'nombre': 'Star Wars Outlaws', 'precio': 69990, 'categoria': 'Juegos de PC', 'tags': 'pc, star wars, mundo abierto, ubisoft', 'descripcion': 'Explora el universo Star Wars en este juego de mundo abierto.'},
    {'nombre': 'Consola Nintendo Switch OLED The Legend of Zelda: Tears of the Kingdom', 'precio': 349990, 'categoria': 'Consolas Nintendo Switch', 'tags': 'consola, switch, oled, zelda', 'descripcion': 'Edición especial de la consola con motivos del aclamado juego.'},
    {'nombre': 'Consola Nintendo Switch 1.1 Neon', 'precio': 299990, 'categoria': 'Consolas Nintendo Switch', 'tags': 'consola, switch, nintendo', 'descripcion': 'La versátil consola de Nintendo en su versión estándar con Joy-Cons color neón.'},
    {'nombre': 'Fuente de Poder para Consola Wii Multivoltaje', 'precio': 12990, 'categoria': 'Accesorios Wii', 'tags': 'accesorio, wii, fuente, poder', 'descripcion': 'Fuente de poder de reemplazo para la consola Nintendo Wii.'},
    {'nombre': 'Carta Pokémon TCG: Charizard ex - SV4.5 Paldean Fates', 'precio': 39990, 'categoria': 'Cartas TCG', 'tags': 'tcg, pokemon, cartas, charizard', 'descripcion': 'Carta individual de alta rareza del popular juego de cartas coleccionables Pokémon.'},
    {'nombre': 'Disney Lorcana: Booster Box The First Chapter', 'precio': 149990, 'categoria': 'Cartas TCG', 'tags': 'tcg, lorcana, disney, cartas', 'descripcion': 'Caja sellada con 24 sobres de la primera edición del juego de cartas Disney Lorcana.'},
    {'nombre': 'Star Wars: Unlimited - Caja de Sobres', 'precio': 129990, 'categoria': 'Cartas TCG', 'tags': 'tcg, star wars, unlimited, cartas', 'descripcion': 'Caja sellada con 24 sobres del nuevo juego de cartas coleccionables de Star Wars.'},
]

def poblar_datos(apps, schema_editor):
    Categoria = apps.get_model('core', 'Categoria')
    Producto = apps.get_model('core', 'Producto')

    categorias_creadas = {}
    for item in PRODUCTOS_DATA:
        nombre_cat = item['categoria']
        if nombre_cat not in categorias_creadas:
            slug = slugify(nombre_cat)
            cat_obj, _ = Categoria.objects.get_or_create(nombre=nombre_cat, defaults={'slug': slug})
            categorias_creadas[nombre_cat] = cat_obj

    for item in PRODUCTOS_DATA:
        categoria_obj = categorias_creadas[item['categoria']]
        Producto.objects.get_or_create(
            nombre=item['nombre'],
            defaults={
                'precio': item['precio'],
                'descripcion': item.get('descripcion', ''),
                'categoria': categoria_obj,
                'tags': item.get('tags', ''),
                'stock': 20,
                'activo': True,
            }
        )

class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')]
    operations = [migrations.RunPython(poblar_datos)]